#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3fchnA2LxE+IqX/RKJYurKAPxvpNGpJriKfjmbWhbz7tbVBSNlniHDviNMhTLdhKOxSIoCDZu3AGVIvTYFy8T1jMAsUia+yc79YGVBP3AaCnP8tWyVhkZJtwr3vs1HuQqThyzFnRgYmzsPQKqEJduN7tq+PLAwlKrynnfAjD9GEIvS8EoAC2Bk9akfaj6l6ccrSrkdjbrA6bc4kyIfkf3PoYpq5pHvlerAE6fTNq2dM15KSqSojunNFU8cIuizy3MnpWmlTT3d+b7/Fh8QQBVtdn3ZZfMMLPbalwqDhBQCVZ9nbV+q8wtZ8tDrLTVwXt9WbJdXuei5zpBsYRtXfTF aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDEirijxHZRaN8tdYpBI0YFt9dZuHWLaAJ+WId1Zx/F46AJSwv0nZbQHf8cSvjWrNAsZXe/OxbLzextUsONanKsCdoIdppHgXersHCNlliHs0HlDL3TdWLfVgRraTEf17OsyscW+abqMrnPx5M4Q0IBDqZKccpuGJHD+5BssWIv+qevOOlU2FbLSk3Y3ctJUXihFqXJ91hjq5iqD48dpi7116BderW0sRv0ljePnF2Dh222ZPiH3jwwm4guKbdT5y86YKFqX60FE9KyVSUehsw40rIgTvFyksZl9d9HOTVQgkNn+jqWbanQ3HFKE9Ea1u6pAw2cO2efO3dHbJev6Nh aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
runcmd:
  - sudo systemctl restart apache2
write_files:
  - path: /var/www/html/info.php
    content: |
      	<?php $ihrname = "Duy Minh Nguyen"; ?>
        <html>
	   <head>
	       <title><?php echo($ihrname) ?></title>
	   </head>
	    <body>
		Filip meets a furry for the first time
	    <br />
	        <img src="https://imagebucketminhtbz.s3.amazonaws.com/IMG-20230930-WA0023.jpg" />
	    </body>
        </html>

    permissions: "0666"
