#cloud-config
users:
  - name: ubuntu #Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL #sudo regeln für diesen User
    groups: users, admin #Gruppen des Users
    home: /home/ubuntu #Home Directory des Users
    shell: /bin/bash #Shell Ordner
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
ssh_pwauth: false #Deaktiviert ssh Passwort Authentifizierung
disable_root: false #Deaktivierung vom Root-Benutzer
package_update: true #Aktualisiert die Packages
packages: #Pakete
  - curl 
  - wget 
